### ISSUE TITLE
Update README with instructions, contributor guidelines, etc.

### ISSUE THREAD

**Issue by hdrake** [COVID-Weather/covid-environmental-factors#10]
Hopefully by tomorrow morning, I will update the [README](https://github.com/COVID-Weather/covid-environmental-factors/blob/master/README.md) with more information on:
1) the general structure of the repository
2) how to install the required (python) packages
3) the use cases for the different python notebooks
4) a basic description of the /output/ files and their intended use
5) guidelines from contributing to the repository

**Comment by glwagner** [comment]
@hdrake I have a few julia scripts that I put together for looking at the JHU data. I'm not sure how useful they'd be to others, but if we want to add them to the repository we could put them in a folder called, say, `/sandbox` (which we can always remove later if its not helpful). Let me know what you think.
