### ISSUE TITLE
Data request broken (full 2019 dataset too large?)

### ISSUE THREAD

**Issue by hdrake** [COVID-Weather/covid-environmental-factors#4]
For some reason the 2019 part of the [ERA5 download script](https://github.com/hdrake/covid-environmental-factors/blob/master/scripts/download_era5_temperature_dewpoint_pressure.py) is broken for me. I was able to download the 2020 data just fine but got an error for the 2019 request. I think this is because we requested too much data for one output file (maybe have to chunk by season or month?)

**Comment by glwagner** [comment]
Closed?

**Comment by hdrake** [comment]
Yep! I've got a local branch where I've extended this to radiation (full & just UV) and preciptiation data as well! I'll put that in a pull request tomorrow.
